config/routes.rb
Rails.application.routes.draw do
  root "drinks#index"
  devise_for :users

  resources :drinks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :drinks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  before_action :set_drink, only: [:show, :edit, :update, :destroy]

  def index
    @drinks = current_user.drinks 
  end

  def show
  end

  def new
    @drink = Drink.new
  end

  def create 
    @drink = current_user.drinks.new(drink_params)
    if @drink.save
      flash[:success] = "Drink Saved"
      redirect_to drinks_path
    else 
      flash[:error] = "Error #{@drink.errors.full_messages.join("\n")}"
      render :new
    end
  end

  def edit
  end 

  def update 
    @drink = Drink.find(params[:id])
    if @drink.update(drink_params)
      redirect_to drink_path 
    else
      render :edit 
    end 
  end

  def destroy
    @drink.destroy
    redirect_to drinks_path
  end


  private 

    def drink_params
      params.require(:drink).permit(:name)
    end

    def set_drink
      @drink = current_user.drinks.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/drinks/edit.html.erb
<h1>Edit Drink </h1>
  <%= form_for @drink do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.submit %>
<% end %>

app/views/drinks/index.html.erb
<style>
 .bg{
  background-color: black;
  color: darkturquoise;
  margin: 20px;
  padding: 20px;
}
</style>
<div class="bg">
<%= button_to "LOG OUT", destroy_user_session_path, class: "ui inverted orange basic button", method: :delete %>
<h1><i class="anchor icon"></i>Howdy <%= current_user.first_name %>!</h1>
<h2><i class="blind icon"></i>Welcome to Drinks R Us</h2>
<hr />
  <%= link_to "Add Drink", new_drink_path, class: "ui inverted basic button" %>
    <h3><i class="glass martini icon"></i> Drink List </h3>
<ul>
<% @drinks.each do |drink| %>
  <li>
    <%= drink.name %>
  <%= link_to "View Drink", drink_path(drink.id), class: "ui inverted teal basic button" %>
  <hr />
  <br />
  
  </li>
<% end %>
</ul>
</div>

app/views/drinks/new.html.erb
<h1>Add Drink</h1>
<%= form_with(model: @drink, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/drinks/show.html.erb
<style>
 .bg{
  background-color: black;
  color: darkturquoise;
  margin: 20px;
  padding: 20px;
}
</style>
<div class="bg">
<h1><%= @drink.name%></h1>
<p>This Drink is the BEES KNEES!</p>
  <%= link_to "Back To Drink List", drinks_path, class: "ui inverted teal basic button" %>
    <i class="glass martini icon"></i>
<hr />
  <%= link_to "Delete Drink", @drink, class: "ui inverted red basic button", method: :delete %>
    <i class="trash alternate outline icon"></i>
<hr />
  <%= link_to "Edit Drink", edit_drink_path, class: "ui inverted teal basic button" %>
    <i class="pencil alternate icon"></i>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstDevise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>